# _config.yml

title: Sailing Vessel Plume
email: "%70%6C%75%6D%65&#64;%66%6C%75%70%65%73.%6F%72%67"
description: >-
  Voyage of a Norsea'27, Plume.
baseurl: "/svplume"
url: "https://flupes.github.io"

show_excerpts: true

theme: minima

plugins:
  - jekyll-feed
  - jekyll_picture_tag

header_pages:
  - journey.md
  - blog.md
  - projects/index.md
  - about.md

responsive_image:
  template: _includes/responsive-image.html
  base_path: assets/media/imgs
  sizes:
    - width: 800
      quality: 65
    - width: 1280
      quality: 75
    - width: 1920
      quality: 85
  strip: true
  save_to_source: false

picture:
  source: "assets/media/imgs"
  output: "assets/media/generated"
  suppress_warnings: true

exclude:
  - README.md
  - INSTALL.md
  - DEPLOY.md

